# Generated by Django 5.2.4 on 2025-07-31 11:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fitness', 'Fitness & Health'), ('cooking', 'Cooking & Recipes'), ('art', 'Art & Design'), ('music', 'Music & Entertainment'), ('lifestyle', 'Lifestyle & Fashion'), ('education', 'Education & Tutorials'), ('adult', 'Adult Content')], default='lifestyle', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='creator_covers/')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('subscription_price', models.DecimalField(decimal_places=2, default=9.99, max_digits=6, validators=[django.core.validators.MinValueValidator(4.99), django.core.validators.MaxValueValidator(49.99)])),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_tips', models.BooleanField(default=True)),
                ('allows_messages', models.BooleanField(default=True)),
                ('is_adult_content', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('youtube', models.CharField(blank=True, max_length=100)),
                ('tiktok', models.CharField(blank=True, max_length=100)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='creators.creator')),
            ],
        ),
    ]
